S01 us43 fix
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #108
Opened 2019-12-11 10:15 UTC by sdesousa

Ajout lien facebook

2019-12-11 13:17 UTC, cnd24 approved these changes

2019-12-11 14:37 UTC, sblondeau requested changes

2019-12-11 14:37 UTC, sblondeau commented on assets/misc/departements-only-france.csv
> +1,01,Ain
ce fichier ne devrait pas etre dans cette PR, et dans tous les cas il ne doit pas etre dans les assets, car pas besoin qu'il soit dispo publiquement

2019-12-11 16:45 UTC, cnd24 approved these changes

2019-12-11 22:13 UTC, sblondeau approved these changes

2019-12-12 14:05 UTC, Toua45 approved these changes

2019-12-12 21:22 UTC, sblondeau approved these changes

2019-12-12 21:22 UTC, merged