S01 us04
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #14
Opened 2019-12-04 13:19 UTC by Stevenbdu

2019-12-04 13:28 UTC, cnd24 requested changes
supprimer les fichiers de migration

2019-12-04 13:37 UTC, cnd24 approved these changes

2019-12-04 13:37 UTC, Stevenbdu commented
> supprimer les fichiers de migration

C'est bon

2019-12-04 15:31 UTC, sblondeau requested changes

2019-12-04 15:31 UTC, sblondeau commented on config/packages/twig_extensions.yaml
> +    #Twig\Extensions\IntlExtension: null
tu peux l'activer, ça sera fait pour les autres, vu que tu l'as installée de toute manière ;-)

2019-12-04 15:31 UTC, sblondeau commented on src/Entity/Blog.php
> +    private $title;
le title doit etre unique (car vous ferez un slug à terme dans une future US => à ajouter au backlog :p) 
rajouter ça coté @ORM (je te laisse chercher) et coté @Assert également (regarde la contrainte UniqueEntity)
Ainsi tu seras sur coté mysql ET coté serveur que ton titre est unique

2019-12-04 15:31 UTC, sblondeau commented on src/Entity/Blog.php
> +     * @Assert\Date
datetime pour la @ORM comme pour @Assert non ?

2019-12-04 15:31 UTC, sblondeau commented on src/Form/BlogType.php
> +                'trim' => true,
le trim est inutilie, true est la valeur par défaut de cette option

2019-12-04 15:31 UTC, sblondeau commented on src/Repository/BlogRepository.php
> +    //  * @return Blog[] Returns an array of Blog objects
enlève le code commenté (meme s'il est généré par Sf ;-))

2019-12-05 09:27 UTC, Stevenbdu commented on src/Entity/Blog.php
> +     * @Assert\Date
J'ai choisi le format date, je trouvais ca plus pertinent

2019-12-05 09:38 UTC, Toua45 approved these changes

2019-12-05 21:56 UTC, sblondeau requested changes

2019-12-05 21:56 UTC, sblondeau commented on src/Repository/BlogRepository.php
> +    public function findByExampleField($value)
non il faut que tu enlèves ce code (qui était commenté de base car c'est juste un exemple généré par le maker)
donc retire les 2 méthodes afin de ne pas avoir de code qui ne sert à rien

2019-12-06 07:43 UTC, sdesousa approved these changes

2019-12-06 08:28 UTC, sdesousa approved these changes

2019-12-06 08:32 UTC, sblondeau approved these changes

2019-12-06 08:32 UTC, merged