S01 us44 fix
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #192
Opened 2019-12-13 17:04 UTC by sdesousa

2019-12-15 16:53 UTC, Helra approved these changes

2019-12-16 12:37 UTC, sblondeau requested changes

2019-12-16 12:37 UTC, sblondeau commented on src/Controller/HomeController.php
> +            ->findBy(['roles' => $roles['Ambassadeur']], null, 6);
faire une constante, par ex NB_CARD pour le nombre à afficher

2019-12-16 13:23 UTC, Helra approved these changes

2019-12-16 22:31 UTC, sblondeau approved these changes

2019-12-16 22:31 UTC, merged