S03 us38 CRUD BRAND + fixture + stylisation edit
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #211
Opened 2020-01-02 15:39 UTC by Helra

2020-01-02 15:59 UTC, sdesousa approved these changes

2020-01-02 16:17 UTC, sblondeau requested changes

2020-01-02 16:17 UTC, sblondeau commented on src/Controller/BrandController.php
> +
message flash a ajouter ;-)

2020-01-02 16:17 UTC, sblondeau commented on src/Entity/Brand.php
> +     * @ORM\Column(type="string", length=150)
ajoute les @assert

2020-01-02 17:09 UTC, sdesousa approved these changes

2020-01-03 11:32 UTC, sblondeau requested changes

2020-01-03 11:32 UTC, sblondeau commented on src/Entity/Brand.php
> +     *      maxMessage = "Votre nom de marque ne doit pas depasser 150 caractères de long")
utilise {{limit}} dans le message d'erreur pour reprendre automatiquement la valeur de 150, sinon si tu modifie le "max" un jour tu risques d'oublier de modif le message

2020-01-03 11:32 UTC, sblondeau commented on src/Entity/Brand.php
> +     *      maxMessage = "Votre recompense ne doit pas depasser 255 caractères de long")
idem partout

2020-01-03 11:32 UTC, sblondeau commented on templates/brand/index.html.twig
> +            </div>
non, c'est dans base.html.twig que tu dois le mettre ! comme ça il est bien présent partout

2020-01-04 17:30 UTC, sdesousa approved these changes

2020-01-06 08:48 UTC, sblondeau requested changes

2020-01-06 08:48 UTC, sblondeau commented on src/Controller/BrandController.php
> +            $this->addFlash('success', 'Votre marque a été modifié');
modifiée non ?

2020-01-06 08:48 UTC, sblondeau commented on src/Form/BrandType.php
> +            ->add('site')
site et instagram se sont des URL ? si oui il faut mettre un UrlType pour avoir un input type url coté form

2020-01-06 08:48 UTC, sblondeau commented on src/Form/BrandType.php
> +            ->add('site')
et par ailleurs si  mettre des @Assert\Url coté entity également, ce qui permet de refaire la verif coté serveur

2020-01-06 08:48 UTC, sblondeau commented on src/Entity/Brand.php
> +     * @ORM\Column(type="string", length=255, nullable=true)
pour site et insta, manque les Assert\Length + (AssertUrl si ce sont bien des URL)

2020-01-06 10:57 UTC, sdesousa approved these changes

2020-01-06 11:21 UTC, sblondeau approved these changes

2020-01-06 15:11 UTC, sdesousa approved these changes

2020-01-06 15:25 UTC, merged