S03 us37 stylisation Brand creation
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #215
Opened 2020-01-02 18:28 UTC by Helra

2020-01-02 19:53 UTC, sdesousa approved these changes

2020-01-03 11:41 UTC, sblondeau requested changes
je comprends pas trop cette US, qui reprend le code de l'autre US... 
il ne faut PAS tirer une branche depuis autre chose que dev, là j'ai les memes erreurs qui dans la US 38 donc pas efficace niveau correction ;-) 
à revoir, on en discute si besoin

2020-01-03 11:41 UTC, sblondeau commented on src/Entity/Brand.php
> +     * @ORM\Column(type="string", length=255, nullable=true)
manque un Assert Length

2020-01-03 11:41 UTC, sblondeau commented on src/Entity/Brand.php
> +     *      maxMessage = "Votre nom de marque ne doit pas depasser 150 caractères de long")
meme remarque que l'autre US

2020-01-07 16:39 UTC, cnd24 approved these changes

2020-01-07 16:47 UTC, sblondeau requested changes

2020-01-07 16:47 UTC, sblondeau commented on templates/brand/index.html.twig
> +    {% for label, messages in app.flashes %}
non, les flash messges uniquement dans le base.html.twig

2020-01-07 16:55 UTC, cnd24 approved these changes

2020-01-07 22:00 UTC, sblondeau approved these changes

2020-01-07 22:00 UTC, merged