S04 us35.4
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #240
Opened 2020-01-06 16:52 UTC by cnd24

pagination pour la page recherche

2020-01-06 17:00 UTC, sdesousa approved these changes

2020-01-06 21:08 UTC, sblondeau requested changes

2020-01-06 21:08 UTC, sblondeau commented on templates/search/index.html.twig
> +            <a class="btn btn-gold mx-5 mb-5" href="{{ path('search_role', {'role': role, 'page': page+1} ) }}">
attention, j'ai peur que tu perdes ce que tu as dans la query string, et donc que tu ne conserves pas tes filtres de page en page, il faut que tu recup ta query string et que tu la rebalance sur tes liens

2020-01-07 14:04 UTC, Stevenbdu approved these changes

2020-01-07 15:33 UTC, sblondeau requested changes

2020-01-07 15:33 UTC, sblondeau commented on templates/search/index.html.twig
> +                   href="{{ path('search_role', {'role': role, 'page': page-1}|merge({'department' : app.request.get('department'), 'category' : app.request.get('category'), 'duty' : app.request.get(
j'ai testé,  href="{{ path('search_role', {'role': role, 'page': page-1}|merge(app.request.query.all)) }}" semble fonctionner, je te laisse modif, ça sera bien plus propre

2020-01-07 16:02 UTC, Stevenbdu approved these changes

2020-01-07 21:59 UTC, sblondeau approved these changes

2020-01-08 07:59 UTC, sdesousa approved these changes

2020-01-08 08:51 UTC, sblondeau approved these changes

2020-01-08 08:51 UTC, merged