S04 us60 tag index
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #265
Opened 2020-01-08 17:01 UTC by sdesousa

2020-01-08 17:02 UTC, cnd24 approved these changes

2020-01-09 12:13 UTC, sblondeau requested changes

2020-01-09 12:13 UTC, sblondeau commented on src/Controller/AdminArticleTagController.php
> +            'article_tags' => $articleTagRepository->findAll(),
orderBy tag name

2020-01-09 12:30 UTC, Toua45 approved these changes

2020-01-09 13:05 UTC, sblondeau approved these changes

2020-01-09 13:09 UTC, Toua45 approved these changes

2020-01-09 13:16 UTC, merged