S01 us44
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #28
Opened 2019-12-05 09:22 UTC by Helra

2019-12-05 14:39 UTC, sdesousa approved these changes

2019-12-05 22:20 UTC, sblondeau requested changes

2019-12-05 22:20 UTC, sblondeau commented on src/Controller/HomeController.php
> +            ->findBy(['roles' => 'ambassadeur'], null, 3);
utilise ici la variable définie dans la classe User, plutot qu'une string "en dur".

2019-12-06 08:01 UTC, sdesousa approved these changes

2019-12-06 08:34 UTC, sblondeau approved these changes

2019-12-06 08:34 UTC, merged