S04 us17 newsletter inscription
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #303
Opened 2020-01-10 12:57 UTC by sdesousa

2020-01-10 13:00 UTC, Toua45 approved these changes

2020-01-10 15:36 UTC, sblondeau requested changes

2020-01-10 15:36 UTC, sblondeau commented on src/Controller/HomeController.php
> +    const MAILCHIMP_API_KEY = '905d1d0295d910a79d373a54c81a7dd2-us4';
non ! une clé API c'est secret, donc dans le .env.local

2020-01-10 15:52 UTC, Toua45 approved these changes

2020-01-12 22:53 UTC, sblondeau approved these changes

2020-01-12 22:53 UTC, merged