add checkbox mentions légales
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #349
Opened 2020-01-13 09:42 UTC by Stevenbdu

2020-01-13 09:48 UTC, Toua45 approved these changes

2020-01-13 10:16 UTC, sblondeau requested changes

2020-01-13 10:16 UTC, sblondeau commented on src/Form/UserInscriptionType.php
> +            ->add('CGV', CheckboxType::class, [
question, au niveau de ta vue, il faudrait à coté de chaque checkbox que tu mettes un lien vers les conditions en question (ou créer une US à faire plus tard si ces pages n'existes pas encore...)
C'est juste mieux en terme d'UX je trouve

2020-01-14 11:02 UTC, Toua45 approved these changes

2020-01-14 12:33 UTC, sblondeau approved these changes

2020-01-14 12:33 UTC, merged