fix pagination nb resultats page1 et autres pages
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #352
Opened 2020-01-13 10:54 UTC by cnd24

2020-01-13 11:08 UTC, Toua45 approved these changes

2020-01-14 08:31 UTC, sblondeau requested changes

2020-01-14 08:31 UTC, sblondeau commented on src/Repository/BlogRepository.php
> +                $firstResult = ($page - 1) * BlogController::NB_MAX_ARTICLES_P1;
pourquoi un NB_MAX_ARTICLES_P1 ? pourquoi c'est pas la meme chose que les autres pages ? et dans ce cas ne peut on pas faire NB_MAX_ARTICLES - 1 ?

2020-01-14 08:39 UTC, cnd24 commented on src/Repository/BlogRepository.php
> +                $firstResult = ($page - 1) * BlogController::NB_MAX_ARTICLES_P1;
La première page contient 1 article à la une + 6 articles, les autres pages contiennent 8 articles

2020-01-14 08:47 UTC, Toua45 approved these changes

2020-01-14 08:53 UTC, sblondeau approved these changes

2020-01-14 08:53 UTC, merged