S05 us10 FAQ admin read
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #359
Opened 2020-01-13 14:59 UTC by sdesousa

2020-01-13 15:08 UTC, Toua45 approved these changes

2020-01-13 15:16 UTC, Toua45 approved these changes

2020-01-14 08:44 UTC, sblondeau requested changes

2020-01-14 08:44 UTC, sblondeau commented on src/Entity/Question.php
> +     * @Assert\NotBlank()
assert length

2020-01-14 08:44 UTC, sblondeau commented on src/Entity/QuestionCategory.php
> +     * @Assert\NotBlank()
assert length

2020-01-14 08:50 UTC, Toua45 approved these changes

2020-01-14 08:56 UTC, sblondeau approved these changes

2020-01-14 08:56 UTC, merged