S05 us37 profil creator
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #360
Opened 2020-01-13 15:47 UTC by Stevenbdu

2020-01-13 16:02 UTC, Toua45 approved these changes

2020-01-14 08:51 UTC, sblondeau requested changes

2020-01-14 08:51 UTC, sblondeau commented on templates/security/profile.html.twig
> +                                     src="https://snap-photos.s3.amazonaws.com/img-thumbs/960w/SYC0YBA37V.jpg"
pas d'images recup direct en ligne, il faut la télécharger

2020-01-14 08:51 UTC, sblondeau commented on templates/security/profile.html.twig
> +                                <h4 class="card-title event">{{ user.brand.name }}</h4>
h4 après un h2

2020-01-14 08:51 UTC, sblondeau commented on templates/security/profile.html.twig
>          {% if is_granted('ROLE_AMBASSADOR') %}
ton twig est long, il pourrait etre interessant de le splitter en 2-3 sous-fichiers que tu vas include

2020-01-15 09:51 UTC, Toua45 approved these changes

2020-01-15 09:57 UTC, sblondeau approved these changes

2020-01-15 09:57 UTC, merged