correction about concept page
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #379
Opened 2020-01-14 14:01 UTC by Toua45

2020-01-14 14:35 UTC, Stevenbdu approved these changes

2020-01-14 14:35 UTC, cnd24 approved these changes

2020-01-14 21:09 UTC, sblondeau requested changes

2020-01-14 21:09 UTC, sblondeau commented on templates/concept/index.html.twig
> +                <h2 class="text-center">Neque porro quisquam est qui dolorem ipsum quia dolor sit amet</h2>
pourquoi on passe d'un vrai texte à du lorem ?

2020-01-15 09:02 UTC, Toua45 commented on templates/concept/index.html.twig
> +                <h2 class="text-center">Neque porro quisquam est qui dolorem ipsum quia dolor sit amet</h2>
C'est parce qu' on avait pas le bon texte, ce contenu ne correspondait pas au concept, elle nous le fournira bientôt

2020-01-15 09:58 UTC, sdesousa approved these changes

2020-01-15 10:20 UTC, merged