ajout du bouton Je m'abonne
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #384
Opened 2020-01-14 16:47 UTC by cnd24

2020-01-14 16:57 UTC, Toua45 approved these changes

2020-01-14 21:16 UTC, sblondeau requested changes

2020-01-14 21:16 UTC, sblondeau commented on templates/subscription/index.html.twig
> +            <a href="#">
pas de button dans un lien. Soit c'est un button dans un form, soit c'est un lien avec une classe btn

2020-01-15 09:00 UTC, Toua45 approved these changes

2020-01-15 11:09 UTC, sblondeau approved these changes

2020-01-15 11:10 UTC, merged