S01 us43 duty
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #39
Opened 2019-12-05 13:56 UTC by sdesousa

2019-12-05 14:01 UTC, cnd24 approved these changes

2019-12-05 15:44 UTC, cnd24 approved these changes

2019-12-10 11:11 UTC, Toua45 approved these changes

2019-12-10 15:20 UTC, sblondeau requested changes
La US 43 est mal rédigée, c'est "je veux créer un nouveau user", or là tu gères des duties, pas des users. Pour moi la US serait plutot "en tant qu'ambassadeur, je veux choisir le type de vente que je souhaite faire"

2019-12-10 15:20 UTC, sblondeau commented on src/Repository/DutyRepository.php
> +    // /**
enlève le code commenté (meme si généré par Sf) ;-)

2019-12-10 15:20 UTC, sblondeau commented on src/DataFixtures/DutyFixtures.php
> +class DutyFixtures extends Fixture
il faudrait que tu mettes aussi à jour le UserFixtures (s'il existe) pour fiare le lien avec les Duty

2019-12-10 15:20 UTC, sblondeau commented on src/Entity/Duty.php
> +     */
ajoute un petit Assert Lenght et NotBlank (meme si tu ne créé jamais de form, ça mange pas de pain ;-))

2019-12-10 16:30 UTC, closed without merging