errors pages done
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #405
Opened 2020-01-15 15:57 UTC by Toua45

2020-01-15 15:59 UTC, cnd24 approved these changes

2020-01-15 17:12 UTC, sdesousa approved these changes

2020-01-15 22:43 UTC, sblondeau requested changes

2020-01-15 22:43 UTC, sblondeau commented on templates/bundles/TwigBundle/Exception/error.html.twig
> +            <img class="error" src="{{ asset('build/error500.png') }}" alt="error-403">
mauvais alt pour l'image

2020-01-16 08:28 UTC, Stevenbdu approved these changes

2020-01-16 09:40 UTC, sblondeau approved these changes

2020-01-16 09:41 UTC, merged