S05_fix_faq w3c
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #410
Opened 2020-01-15 16:44 UTC by sdesousa

fix w3c duplicate id in FAQ and <a> nesting in search

2020-01-15 16:46 UTC, cnd24 approved these changes

2020-01-15 22:54 UTC, sblondeau requested changes

2020-01-15 22:54 UTC, sblondeau commented on templates/question/index.html.twig
> +                        <div id="collapse{{- loop.index -}}" class="collapse" aria-labelledby="heading{{- loop.index -}}" data-parent="#accordionExample{{- i -}}">
pourquoi des fois tu utilises loop.index direct et des fois {{ i }} ? met loop.index partout plutot

2020-01-16 07:38 UTC, sdesousa commented on templates/question/index.html.twig
> +                        <div id="collapse{{- loop.index -}}" class="collapse" aria-labelledby="heading{{- loop.index -}}" data-parent="#accordionExample{{- i -}}">
C'est pas le même loop.index, j'ai deux boucles

2020-01-16 08:33 UTC, Toua45 approved these changes

2020-01-16 09:42 UTC, sblondeau approved these changes

2020-01-16 09:42 UTC, merged