S05 fix profil
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #422
Opened 2020-01-16 18:49 UTC by sdesousa

2020-01-17 08:00 UTC, Toua45 approved these changes

2020-01-17 08:33 UTC, sblondeau requested changes

2020-01-17 08:33 UTC, sblondeau commented on src/Controller/UserController.php
> +        return $this->render($view, $options);
vu que l'$option est facultative, je trouve ça plus propre de faire deux return $this->render, c'est plus clair je trouve. J'aime pas trop le fait de mettre le nom du template dans une variable.
De plus, tu peux optimiser le check des roles avec $this->isGranted()  à vérifier si on peut passer un objet $user en second paramètre (je pense que oui mais c'est pas clair sur la doc) ou si c'est uniquement réservé à l'user actuellement connecté.
https://symfony.com/doc/current/security.html#hierarchical-roles


petite optimisation
```
    public function show(User $user, EventRepository $eventRepository): Response
    {
         if ($this->isGranted('ROLE_AMBASSADOR,$user->getRoles())) { 
             $events = $eventRepository->findByUser($user); 
            return $this->render('user/show_ambassador.html.twig', ['events'=>$events]); 
         } elseif ($this->isGranted('ROLE_CREATOR',$user->getRoles())) { 
            return $this->render('user/show_creator.html.twig'); 
        }
}
```

2020-01-20 15:01 UTC, Toua45 approved these changes

2020-01-20 15:04 UTC, sblondeau approved these changes

2020-01-20 15:20 UTC, cnd24 approved these changes

2020-01-20 15:51 UTC, merged