champs brand nullable
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #532
Opened 2020-01-24 10:25 UTC by Stevenbdu

2020-01-24 10:52 UTC, cnd24 approved these changes

2020-01-25 12:20 UTC, sblondeau requested changes

2020-01-25 12:20 UTC, sblondeau commented on templates/security/_creatorPartProfile.html.twig
> +                            <button type="button" class="btn btn-gold mt-5">Créer ma marque</button>
pas de button dans un a, ni le contraire ! 
les classes btn s'appliquent aux deux indistinctement. Ici un `<a class="btn btn-gold">` suffit donc largement

2020-01-25 12:20 UTC, sblondeau commented on templates/security/_creatorPartProfile.html.twig
> +                <button type="button" class="btn btn-gold">Votre galerie</button>
idem

2020-01-27 09:28 UTC, Helra approved these changes

2020-01-27 09:41 UTC, sblondeau approved these changes

2020-01-27 09:41 UTC, merged