category files show and index done
WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs pull request #84
Opened 2019-12-09 12:09 UTC by Toua45

2019-12-09 12:21 UTC, sdesousa requested changes

2019-12-09 12:21 UTC, sdesousa commented on src/Repository/CategoryRepository.php
> +    */
retire le code commenté

2019-12-09 12:24 UTC, Toua45 commented on src/Repository/CategoryRepository.php
> +    */
Correction effectuée

2019-12-09 12:26 UTC, sdesousa approved these changes

2019-12-09 16:29 UTC, sblondeau requested changes
profite de cette US pour ajouter une classe CategoryFixture

2019-12-09 16:29 UTC, sblondeau commented on templates/category/index.html.twig
> +                <td colspan="3">Aucune catégories trouvées</td>
singulier

2019-12-09 17:01 UTC, Toua45 commented on templates/category/index.html.twig
> +                <td colspan="3">Aucune catégories trouvées</td>
Correction effectuée

2019-12-09 19:53 UTC, sdesousa approved these changes

2019-12-09 21:08 UTC, sblondeau requested changes

2019-12-09 21:08 UTC, sblondeau commented on src/DataFixtures/CategoryFixtures.php
> +        for ($i = 0; $i < 10; $i++) {
cette boucle est en trop non ?

2019-12-10 09:32 UTC, Toua45 commented on src/DataFixtures/CategoryFixtures.php
> +        for ($i = 0; $i < 10; $i++) {
Correction effectuée

2019-12-10 09:34 UTC, sdesousa approved these changes

2019-12-10 16:10 UTC, sblondeau approved these changes

2019-12-10 16:10 UTC, merged